FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY success.html /usr/share/nginx/html/success.html
COPY game.html /usr/share/nginx/html/game.html
