server {
    listen 5002 ssl;
    server_name localhost;
    access_log /var/log/nginx/access.log combined;
    charset utf-8;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    location / {
        default_type text/html;
        add_header Cache-Control no-cache;
	alias /usr/share/nginx/html/;
    }
    location /success {
        default_type text/html;
        add_header Cache-Control no-cache;
        alias /usr/share/nginx/html/success.html;
    }
    location /game {
        default_type text/html;
        add_header Cache-Control no-cache;
        alias /usr/share/nginx/html/game.html;
    }
}